//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEMPO.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MiscTimeLog
    {
        public int mmtid { get; set; }
        public Nullable<int> entryid { get; set; }
        public Nullable<int> worktypeid { get; set; }
        public Nullable<int> projectid { get; set; }
    
        public virtual TimeEntry timeentry { get; set; }
        public virtual Project project { get; set; }
        public virtual WorkType worktype { get; set; }
    }
}
