//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEMPO.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectList
    {
        public string ProjectName { get; set; }
        public int projectid { get; set; }
        public Nullable<int> clientid { get; set; }
        public int jobnumyear { get; set; }
        public string jobnum { get; set; }
        public string refjobnum { get; set; }
        public Nullable<int> projecttypeid { get; set; }
        public string description { get; set; }
    }
}
