//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEMPO.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public project()
        {
            this.mmts = new HashSet<mmt>();
            this.timeentries = new HashSet<timeentry>();
        }
    
        public int projectid { get; set; }
        public Nullable<int> clientid { get; set; }
        public int jobnumyear { get; set; }
        public string jobnum { get; set; }
        public string refjobnum { get; set; }
        public Nullable<int> projecttypeid { get; set; }
        public string description { get; set; }
    
        public virtual client client { get; set; }
        public virtual JobYear JobYear { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mmt> mmts { get; set; }
        public virtual projecttype projecttype { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<timeentry> timeentries { get; set; }
    }
}
