//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEMPO.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectSummary
    {
        public int projectid { get; set; }
        public Nullable<int> clientid { get; set; }
        public string jobnum { get; set; }
        public string refjobnum { get; set; }
        public string projecttypedesc { get; set; }
        public string description { get; set; }
        public bool active { get; set; }
        public int JobYear { get; set; }
        public Nullable<decimal> InternalAmount { get; set; }
        public Nullable<decimal> TotalHours { get; set; }
        public Nullable<System.DateTime> lastHoursLogged { get; set; }
        public string clientname { get; set; }
    }
}
