//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEMPO.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class timesheet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public timesheet()
        {
            this.timeentries = new HashSet<timeentry>();
        }
    
        public int tid { get; set; }
        public Nullable<int> peid { get; set; }
        public Nullable<int> empid { get; set; }
        public Nullable<int> statusid { get; set; }
        public string notes { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual periodending periodending { get; set; }
        public virtual status status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<timeentry> timeentries { get; set; }
    }
}
