//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEMPO.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeEntry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TimeEntry()
        {
            this.mmts = new HashSet<MiscTimeLog>();
        }
    
        public int entryid { get; set; }
        public Nullable<int> tid { get; set; }
        public Nullable<decimal> sunday { get; set; }
        public Nullable<decimal> monday { get; set; }
        public Nullable<decimal> tuesday { get; set; }
        public Nullable<decimal> wednesday { get; set; }
        public Nullable<decimal> thursday { get; set; }
        public Nullable<decimal> friday { get; set; }
        public Nullable<decimal> saturday { get; set; }
        public Nullable<int> worktypeid { get; set; }
        public Nullable<int> projectid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MiscTimeLog> mmts { get; set; }
        public virtual Project project { get; set; }
        public virtual TimeSheet timesheet { get; set; }
        public virtual WorkType worktype { get; set; }
    }
}
