//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3705.288
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.0.3705.288.
// 
namespace TEMPO.Client.TempoFacade {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TempoSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BusinessRule))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BusinessEntity))]
    public class Tempo : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public Tempo() {
            this.Url = "http://localhost/TempoFacade/tempo.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Employee Login(string username, string password) {
            object[] results = this.Invoke("Login", new object[] {
                        username,
                        password});
            return ((Employee)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginLogin(string username, string password, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Login", new object[] {
                        username,
                        password}, callback, asyncState);
        }
        
        /// <remarks/>
        public Employee EndLogin(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Employee)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSecurityContext", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SecurityContext GetSecurityContext() {
            object[] results = this.Invoke("GetSecurityContext", new object[0]);
            return ((SecurityContext)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetSecurityContext(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetSecurityContext", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public SecurityContext EndGetSecurityContext(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SecurityContext)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SearchTimeSheets", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TimeSheet[] SearchTimeSheets(int employeeID, string date1, string date2, SearchType searchtype) {
            object[] results = this.Invoke("SearchTimeSheets", new object[] {
                        employeeID,
                        date1,
                        date2,
                        searchtype});
            return ((TimeSheet[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSearchTimeSheets(int employeeID, string date1, string date2, SearchType searchtype, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SearchTimeSheets", new object[] {
                        employeeID,
                        date1,
                        date2,
                        searchtype}, callback, asyncState);
        }
        
        /// <remarks/>
        public TimeSheet[] EndSearchTimeSheets(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TimeSheet[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getLookUpVal_Status", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Status[] getLookUpVal_Status() {
            object[] results = this.Invoke("getLookUpVal_Status", new object[0]);
            return ((Status[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetLookUpVal_Status(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getLookUpVal_Status", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public Status[] EndgetLookUpVal_Status(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Status[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getLookUpVal_Client", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Client[] getLookUpVal_Client() {
            object[] results = this.Invoke("getLookUpVal_Client", new object[0]);
            return ((Client[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetLookUpVal_Client(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getLookUpVal_Client", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public Client[] EndgetLookUpVal_Client(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Client[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getLookUpVal_Project", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Project[] getLookUpVal_Project(int clientid) {
            object[] results = this.Invoke("getLookUpVal_Project", new object[] {
                        clientid});
            return ((Project[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetLookUpVal_Project(int clientid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getLookUpVal_Project", new object[] {
                        clientid}, callback, asyncState);
        }
        
        /// <remarks/>
        public Project[] EndgetLookUpVal_Project(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Project[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getLookUpVal_WorkType", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WorkType[] getLookUpVal_WorkType() {
            object[] results = this.Invoke("getLookUpVal_WorkType", new object[0]);
            return ((WorkType[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetLookUpVal_WorkType(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getLookUpVal_WorkType", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public WorkType[] EndgetLookUpVal_WorkType(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((WorkType[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/updateTimeSheet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool updateTimeSheet(TimeSheet ts) {
            object[] results = this.Invoke("updateTimeSheet", new object[] {
                        ts});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginupdateTimeSheet(TimeSheet ts, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("updateTimeSheet", new object[] {
                        ts}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndupdateTimeSheet(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public class Employee : BusinessEntity {
        
        /// <remarks/>
        public int EmployeeID;
        
        /// <remarks/>
        public string EmployeeName;
        
        /// <remarks/>
        public string Password;
        
        /// <remarks/>
        public System.Double Rate;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Status))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProjectType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Client))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Project))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WorkType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TimeEntry))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PeriodEnding))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TimeSheet))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Employee))]
    public abstract class BusinessEntity {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SecurityContext))]
    public abstract class BusinessRule {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public class SecurityContext : BusinessRule {
        
        /// <remarks/>
        public bool MODAUTH_TimeSheet;
        
        /// <remarks/>
        public bool MODAUTH_Reports;
        
        /// <remarks/>
        public bool MODAUTH_Admin;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public class Status : BusinessEntity {
        
        /// <remarks/>
        public int StatusID;
        
        /// <remarks/>
        public string StatusName;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public class ProjectType : BusinessEntity {
        
        /// <remarks/>
        public int ProjectTypeID;
        
        /// <remarks/>
        public string ProjectTypeDescription;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public class Client : BusinessEntity {
        
        /// <remarks/>
        public int ClientID;
        
        /// <remarks/>
        public string ClientName;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public class Project : BusinessEntity {
        
        /// <remarks/>
        public int ProjectID;
        
        /// <remarks/>
        public Client Client;
        
        /// <remarks/>
        public int JobNumberYear;
        
        /// <remarks/>
        public string JobNumber;
        
        /// <remarks/>
        public string RefernceJobNumber;
        
        /// <remarks/>
        public ProjectType ProjectType;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public class WorkType : BusinessEntity {
        
        /// <remarks/>
        public int TypeID;
        
        /// <remarks/>
        public string TypeName;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public class TimeEntry : BusinessEntity {
        
        /// <remarks/>
        public int EntryID;
        
        /// <remarks/>
        public System.Double[] Hours;
        
        /// <remarks/>
        public WorkType WorkType;
        
        /// <remarks/>
        public Project Project;
        
        /// <remarks/>
        public Client Client;
        
        /// <remarks/>
        public string Notes;
        
        /// <remarks/>
        public int TimeSheetID;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public class PeriodEnding : BusinessEntity {
        
        /// <remarks/>
        public string PeriodEndingDate;
        
        /// <remarks/>
        public int PeriodEndingID;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public class TimeSheet : BusinessEntity {
        
        /// <remarks/>
        public Employee Employee;
        
        /// <remarks/>
        public PeriodEnding PeriodEnding;
        
        /// <remarks/>
        public int TimeSheetID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LineItems")]
        public TimeEntry[] LineItems;
        
        /// <remarks/>
        public Status TimeSheetStatus;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum SearchType {
        
        /// <remarks/>
        DateEmp,
        
        /// <remarks/>
        SavedEmp,
    }
}
